/* AUTO-GENERATED by tools/build.js — folder-size snapshot. Do not edit. */
'use strict';
export const SIZE_MANIFEST = {
  "totalBytes": 53334163,
  "fileCount": 358,
  "generatedAt": "2026-05-30",
  "categories": [
    {
      "key": "video",
      "label": "Videos",
      "bytes": 21914674,
      "files": 8
    },
    {
      "key": "audio",
      "label": "Audio",
      "bytes": 19769171,
      "files": 300
    },
    {
      "key": "image",
      "label": "Images",
      "bytes": 11077711,
      "files": 11
    },
    {
      "key": "code",
      "label": "Code",
      "bytes": 569584,
      "files": 37
    },
    {
      "key": "other",
      "label": "Other",
      "bytes": 3023,
      "files": 2
    }
  ]
};
