/* AUTO-GENERATED by tools/build.js — folder-size snapshot. Do not edit. */
'use strict';
export const SIZE_MANIFEST = {
  "totalBytes": 49826918,
  "fileCount": 354,
  "generatedAt": "2026-05-30",
  "categories": [
    {
      "key": "audio",
      "label": "Audio",
      "bytes": 19769171,
      "files": 300
    },
    {
      "key": "video",
      "label": "Videos",
      "bytes": 18420506,
      "files": 7
    },
    {
      "key": "image",
      "label": "Images",
      "bytes": 11077711,
      "files": 11
    },
    {
      "key": "code",
      "label": "Code",
      "bytes": 558522,
      "files": 35
    },
    {
      "key": "other",
      "label": "Other",
      "bytes": 1008,
      "files": 1
    }
  ]
};
