/**
 * @module game-size
 * @description The "GAME SIZE" popup — opened from the options drawer. Shows the
 * total size of the whole game folder plus a color-coded breakdown (videos,
 * audio, images, code, other), styled to match the sim/math stat panels.
 *
 * The numbers come from SIZE_MANIFEST in src/panels/size-manifest.js, which is regenerated by
 * tools/build.js on every build — so the figure is accurate as of the last build.
 */
'use strict';

import { SIZE_MANIFEST } from './size-manifest.js';

/* per-category icon + colour (matched to the manifest's category keys) */
const CAT_META = {
  video: { icon: '🎬', color: '#B07CF0' },
  audio: { icon: '🔊', color: '#2EE85A' },
  image: { icon: '🖼️', color: '#F5C400' },
  code:  { icon: '💻', color: '#40D8FF' },
  other: { icon: '📦', color: '#8899AA' },
};

const btnSize   = document.getElementById('btn-size');
const modal     = document.getElementById('size-modal');
const closeBtn  = document.getElementById('btn-close-size');
const doneBtn   = document.getElementById('btn-size-done');
const totalEl   = document.getElementById('size-total');
const scopeEl   = document.getElementById('size-scope');
const phasesEl  = document.getElementById('size-phases');
const barEl     = document.getElementById('size-bar');
const legendEl  = document.getElementById('size-legend');

const MB = bytes => bytes / 1048576;
function fmtSize(bytes) {
  const m = MB(bytes);
  if (m >= 1)  return `${m.toFixed(m >= 10 ? 1 : 2)} MB`;
  return `${(bytes / 1024).toFixed(0)} KB`;
}

/** Build the popup contents from the manifest (once). */
function render() {
  const { totalBytes, fileCount, generatedAt, categories, player, dev,
          firstPlay, progressive } = SIZE_MANIFEST;
  if (!totalBytes) return;
  const pct = b => (b / totalBytes) * 100;

  // total headline
  if (totalEl) {
    totalEl.innerHTML =
      `<span class="size-total-num">${MB(totalBytes).toFixed(1)}</span>` +
      `<span class="size-total-unit">MB</span>` +
      `<span class="size-total-sub">${fileCount.toLocaleString()} files · snapshot ${generatedAt}</span>`;
  }

  // player-build vs dev/gaff-tools split (what ships to players vs dev-only)
  if (scopeEl && player && dev) {
    const wp = (player.bytes / totalBytes) * 100;
    scopeEl.innerHTML =
      `<div class="size-scope-bar">` +
        `<div class="size-scope-seg player" style="width:${wp}%"></div>` +
        `<div class="size-scope-seg dev" style="width:${100 - wp}%"></div>` +
      `</div>` +
      `<div class="size-scope-rows">` +
        `<div class="size-scope-row"><span class="size-scope-dot player"></span>` +
          `<span class="size-scope-name">📦 Player build</span>` +
          `<span class="size-scope-meta">${player.files.toLocaleString()} files</span>` +
          `<span class="size-scope-val">${fmtSize(player.bytes)}</span></div>` +
        `<div class="size-scope-row"><span class="size-scope-dot dev"></span>` +
          `<span class="size-scope-name">🛠 Dev / gaff tools</span>` +
          `<span class="size-scope-meta">${dev.files.toLocaleString()} files</span>` +
          `<span class="size-scope-val">${fmtSize(dev.bytes)}</span></div>` +
      `</div>`;
  }

  // download footprint — how much loads, and WHEN (bars relative to the on-disk total)
  if (phasesEl && player && firstPlay && progressive) {
    const max = totalBytes || 1;
    const firstPctOfWeb = player.bytes ? Math.round((firstPlay.bytes / player.bytes) * 100) : 0;
    const row = (cls, icon, name, sub, b, files) =>
      `<div class="size-phase-row">` +
        `<div class="size-phase-head">` +
          `<span class="size-phase-name">${icon} ${name}</span>` +
          `<span class="size-phase-val">${fmtSize(b)}</span>` +
        `</div>` +
        `<div class="size-phase-track">` +
          `<div class="size-phase-fill ${cls}" style="width:${((b / max) * 100).toFixed(1)}%"></div>` +
        `</div>` +
        `<div class="size-phase-sub"><span>${sub}</span>` +
          `<span class="size-phase-files">${files.toLocaleString()} files</span></div>` +
      `</div>`;
    phasesEl.innerHTML =
      `<div class="size-phases-title">📡 What downloads, and when</div>` +
      row('machine', '💻', 'On your machine',           'Full project, including dev tools',          totalBytes,        fileCount) +
      row('web',     '🌐', 'Deployed to the web',        "What's uploaded to Netlify",                player.bytes,      player.files) +
      row('first',   '⚡', 'Loads before the first spin', 'Code, reels, base music & the page videos',  firstPlay.bytes,   firstPlay.files) +
      row('lazy',    '🌙', 'Streams in afterwards',       'Bonus, voice lines & wolf reaction clips',   progressive.bytes, progressive.files) +
      `<p class="size-phases-note">Only <b>${fmtSize(firstPlay.bytes)}</b> (${firstPctOfWeb}% of the live site) downloads before you can play — the rest streams in quietly in the background or on demand.</p>`;
  }

  // stacked bar
  if (barEl) {
    barEl.innerHTML = '';
    categories.forEach(c => {
      const seg = document.createElement('div');
      seg.className = 'size-bar-seg';
      seg.style.width = `${pct(c.bytes)}%`;
      seg.style.background = (CAT_META[c.key] || CAT_META.other).color;
      seg.title = `${c.label}: ${fmtSize(c.bytes)}`;
      barEl.appendChild(seg);
    });
  }

  // legend rows
  if (legendEl) {
    legendEl.innerHTML = '';
    categories.forEach(c => {
      const meta = CAT_META[c.key] || CAT_META.other;
      const row = document.createElement('div');
      row.className = 'size-leg-row';
      row.innerHTML =
        `<span class="size-swatch" style="background:${meta.color}"></span>` +
        `<span class="size-leg-name">${meta.icon} ${c.label}</span>` +
        `<span class="size-leg-pct">${pct(c.bytes).toFixed(0)}%</span>` +
        `<span class="size-leg-files">${c.files.toLocaleString()} file${c.files === 1 ? '' : 's'}</span>` +
        `<span class="size-leg-val">${fmtSize(c.bytes)}</span>`;
      legendEl.appendChild(row);
    });
  }
}

function openModal()  { modal.classList.remove('hidden'); }
function closeModal() { modal.classList.add('hidden'); }

if (btnSize && modal) {
  render();
  btnSize.addEventListener('click', openModal);
  if (closeBtn) closeBtn.addEventListener('click', closeModal);
  if (doneBtn) doneBtn.addEventListener('click', closeModal);
  modal.addEventListener('click', e => { if (e.target === modal) closeModal(); });
}
