/**
 * @module game-size
 * @description The "GAME SIZE" popup — opened from the options drawer. Shows the
 * total size of the whole game folder plus a color-coded breakdown (videos,
 * audio, images, code, other), styled to match the sim/math stat panels.
 *
 * The numbers come from SIZE_MANIFEST in src/panels/size-manifest.js, which is regenerated by
 * tools/build.js on every build — so the figure is accurate as of the last build.
 */
'use strict';

import { SIZE_MANIFEST } from './size-manifest.js';

/* per-category icon + colour (matched to the manifest's category keys) */
const CAT_META = {
  video: { icon: '🎬', color: '#B07CF0' },
  audio: { icon: '🔊', color: '#2EE85A' },
  image: { icon: '🖼️', color: '#F5C400' },
  code:  { icon: '💻', color: '#40D8FF' },
  other: { icon: '📦', color: '#8899AA' },
};

const btnSize   = document.getElementById('btn-size');
const modal     = document.getElementById('size-modal');
const closeBtn  = document.getElementById('btn-close-size');
const doneBtn   = document.getElementById('btn-size-done');
const totalEl   = document.getElementById('size-total');
const barEl     = document.getElementById('size-bar');
const legendEl  = document.getElementById('size-legend');

const MB = bytes => bytes / 1048576;
function fmtSize(bytes) {
  const m = MB(bytes);
  if (m >= 1)  return `${m.toFixed(m >= 10 ? 1 : 2)} MB`;
  return `${(bytes / 1024).toFixed(0)} KB`;
}

/** Build the popup contents from the manifest (once). */
function render() {
  const { totalBytes, fileCount, generatedAt, categories } = SIZE_MANIFEST;
  if (!totalBytes) return;
  const pct = b => (b / totalBytes) * 100;

  // total headline
  if (totalEl) {
    totalEl.innerHTML =
      `<span class="size-total-num">${MB(totalBytes).toFixed(1)}</span>` +
      `<span class="size-total-unit">MB</span>` +
      `<span class="size-total-sub">${fileCount.toLocaleString()} files · snapshot ${generatedAt}</span>`;
  }

  // stacked bar
  if (barEl) {
    barEl.innerHTML = '';
    categories.forEach(c => {
      const seg = document.createElement('div');
      seg.className = 'size-bar-seg';
      seg.style.width = `${pct(c.bytes)}%`;
      seg.style.background = (CAT_META[c.key] || CAT_META.other).color;
      seg.title = `${c.label}: ${fmtSize(c.bytes)}`;
      barEl.appendChild(seg);
    });
  }

  // legend rows
  if (legendEl) {
    legendEl.innerHTML = '';
    categories.forEach(c => {
      const meta = CAT_META[c.key] || CAT_META.other;
      const row = document.createElement('div');
      row.className = 'size-leg-row';
      row.innerHTML =
        `<span class="size-swatch" style="background:${meta.color}"></span>` +
        `<span class="size-leg-name">${meta.icon} ${c.label}</span>` +
        `<span class="size-leg-pct">${pct(c.bytes).toFixed(0)}%</span>` +
        `<span class="size-leg-files">${c.files.toLocaleString()} file${c.files === 1 ? '' : 's'}</span>` +
        `<span class="size-leg-val">${fmtSize(c.bytes)}</span>`;
      legendEl.appendChild(row);
    });
  }
}

function openModal()  { modal.classList.remove('hidden'); }
function closeModal() { modal.classList.add('hidden'); }

if (btnSize && modal) {
  render();
  btnSize.addEventListener('click', openModal);
  if (closeBtn) closeBtn.addEventListener('click', closeModal);
  if (doneBtn) doneBtn.addEventListener('click', closeModal);
  modal.addEventListener('click', e => { if (e.target === modal) closeModal(); });
}
