/**
 * @module phrases
 * @description Every line the narrator can say, in the voice of the BIG BAD WOLF —
 * a gruff cowboy wolf straight out of the Three Little Pigs. Grouped by game event.
 *
 * This is the SINGLE source of truth for the narrator script. It's imported by:
 *   • js/narrator.js   – picks a random line per event and plays the matching MP3
 *   • tools/voice.js   – generates the MP3s from ElevenLabs (one file per line)
 *
 * Files live at  assets/audio/narrator/<category>_<index>.mp3  where <index> is the
 * line's position in its array. So the array order here defines which file is which —
 * if you re-order or change counts, re-run `node tools/voice.js all <voiceId>`.
 */
'use strict';

export const PHRASES = {
  spin: [
    "Alright partner, let's give them reels a spin!",
    "Heeere we go now — round and round she goes!",
    "Spin 'em up, and let's see what the wind blows in!",
    "Ooo-wee! Let's rattle them reels, partner!",
    "Come on now, daddy needs a new pair o' boots!",
    "Awooo! Let 'er rip!",
    "Let's huff up a storm and spin this thing!",
    "Round the reels go — where they stop, heh, only I know!",
    "Crank 'er up, partner — I got a hankerin' for a win!",
    "Spinnin' faster'n a tumbleweed in a twister!",
    "Let's see if them pigs left us anything good!",
    "Hold onto your hat — here she spins!",
    "I feel a lucky wind a-blowin', partner!",
    "Saddle up! These reels are about to ride!",
    "One good huff oughta get these reels movin'!",
    "Come on, sugar — show ol' Wolf somethin' sweet!",
    "Reels a-turnin', and my belly's a-rumblin'!",
    "Yeehaw! Down the trail we go!",
    "Spin it like you mean it, partner!",
    "Let's blow the doors off this one!",
    "Here comes the big bad spin, little piggies!",
    "My whiskers are twitchin' — that means money!",
    "Let's kick up some dust on these here reels!",
    "Come on now, line 'em up like ducks in a row!",
    "Easy does it... and... SPIN!",
    "Wind's at our back, partner — let 'er fly!",
    "Give 'er a whirl! Fortune favors the hungry!",
    "Round we go — I can almost taste them winnins!",
  ],
  smallWin: [
    "Well lookie there — a lil' nibble!",
    "Heh, ain't much, but a wolf don't turn down a snack!",
    "A few coins for the den! I'll take it!",
    "That there's an appetizer, partner!",
    "Small bite, but tasty all the same!",
    "Cha-ching — that's some kibble money!",
    "Not a feast, but it'll hold me over!",
    "A lil' somethin' for the chinny-chin-chin!",
    "Coins in the coat, partner — every bit counts!",
    "Heh heh, them pigs dropped a few on the way out!",
    "A modest haul, but ol' Wolf is patient!",
    "That'll buy me a new neckerchief at least!",
    "Small win, big appetite — keep 'em comin'!",
    "Pocket change, but my pockets run deep!",
    "A nibble here, a nibble there — adds up, partner!",
    "Yeehaw, a little drizzle 'fore the storm!",
    "I've et smaller, partner — we'll take it!",
    "Couple coins jingle-jangle — music to my ears!",
  ],
  mediumWin: [
    "Now we're cookin' with bacon grease!",
    "Ooo-wee! That's a proper meal right there!",
    "Heh heh HEH! The pigs are payin' up!",
    "Now THAT'S a haul worth howlin' about! Awooo!",
    "Look at them coins runnin' like scared piggies!",
    "That's the good stuff, partner — sink yer teeth in!",
    "A solid bite outta this here game!",
    "Yeehaw! The wind's blowin' our way!",
    "That'll fill the den AND the belly!",
    "Mighty fine payout, partner — mighty fine!",
    "Them reels finally came to their senses!",
    "Oh, I'm lickin' my chops over this one!",
    "Now we're talkin' real wolf money!",
    "That's a wagon-load of coins, partner!",
    "Huff, puff, and PAYDAY! Beautiful!",
    "The pigs are squealin' and I'm grinnin'!",
    "A fine cut of winnins, served up hot!",
    "Ringin' the dinner bell on that one!",
  ],
  bigWin: [
    "AWOOOOO! Now THAT is a feast, partner!",
    "WELL SLAP MY TAIL AND CALL ME LUCKY!",
    "HOO-WEE! The whole dang henhouse just paid out!",
    "I HUFFED, I PUFFED, AND I BLEW THE BANK WIDE OPEN!",
    "GREAT GALLOPIN' GOLD! LOOK AT THEM COINS!",
    "NOT BY THE HAIR — THIS HERE'S A MONSTER, PARTNER!",
    "YEEEEHAW! BIGGEST HAUL THIS SIDE O' THE FOREST!",
    "THEM PIGS DONE LEFT THE WHOLE TREASURE BEHIND!",
    "I'M HOWLIN' AT THE MOON OVER THIS ONE! AWOOO!",
    "STAMPEDE OF COINS, PARTNER — GET OUTTA THE WAY!",
    "MY CHINNY-CHIN-CHIN IS TREMBLIN' WITH JOY!",
    "BLOW ME DOWN — THAT'S A FORTUNE!",
    "HOT DIGGITY WOLF, WE STRUCK IT RICH!",
    "RING THE DINNER BELL — IT'S A BANQUET!",
    "I AIN'T NEVER SEEN SO MANY COINS IN ALL MY DAYS!",
    "THE BIG BAD WOLF HITS THE BIG BAD JACKPOT!",
    "GRAB A BUCKET, PARTNER — IT'S RAININ' GOLD!",
    "MY WHISKERS 'BOUT FELL OFF — WHAT A WIN!",
    "WOOOO! TELL THE WHOLE FOREST WE DONE IT!",
    "THIS HERE'S A WIN FER THE STORYBOOKS!",
  ],
  loss: [
    "Aw, shucks — empty as a pig pen at suppertime.",
    "Nothin' but tumbleweeds on that one, partner.",
    "Hmph. Them pigs got away clean that round.",
    "Dry as the desert. Shake it off, partner.",
    "No bacon this time. We huff again!",
    "Ah well — even a wolf misses a meal now and then.",
    "The wind died down on that one. Reload them lungs!",
    "Nothin' in the henhouse. Onward!",
    "Them reels are playin' coy. I like a challenge.",
    "Missed 'em by a whisker. We'll get 'em next time.",
    "No coins, no problem — a wolf is patient.",
    "That house didn't budge. Bigger huff next round!",
    "Empty-pawed, but not for long, partner.",
    "Heh, them pigs think they're safe. Cute.",
    "Dust in the wind. Let's spin her again.",
    "A swing and a miss. Sharpen them claws!",
    "Not a crumb that time. My belly grumbles on.",
    "Quiet round. Calm 'fore the big bad storm.",
  ],
  lossStreak: [
    "Come on now — them pigs can't hide forever!",
    "Dang it all, this dry spell's testin' my patience!",
    "A wolf's gotta eat! Throw me a bone here!",
    "Been a long, dusty trail without a meal...",
    "I've huffed till I'm blue — somethin's gotta give!",
    "Them three pigs are gettin' cocky. Won't last!",
    "Every drought ends in a downpour, partner. Hold fast!",
    "I can smell a big win comin' over the ridge!",
    "These reels OWE me — and a wolf always collects!",
    "Lean times, partner — but the wolf endures!",
    "I've gone hungrier'n this and still ate good!",
    "The bricks are holdin' for now. Keep huffin'!",
    "Patience, partner. Even the moon takes its time.",
    "My luck's 'bout to turn like the prairie wind!",
    "Storm's been brewin' — any spin now she breaks!",
    "Keep the faith — the big bad payday's comin'!",
  ],
  nearMiss: [
    "Ooo! Nearly had them pigs by the tail!",
    "One whisker away! ONE! Dadgummit!",
    "So close I could smell the bacon fryin'!",
    "Argh — that house near 'bout came down!",
    "Them pigs slipped out the back door, partner!",
    "A hair! Not by the hair of my chinny-chin-chin!",
    "Teasin' me, are ya? Them reels are cruel!",
    "I had 'em cornered and they wriggled free!",
    "Almost blew it down! One more gust!",
    "My chops were waterin' — and POOF, gone!",
    "Right there! It was RIGHT there, partner!",
    "Close enough to feel the wind change!",
  ],
  bonusTrigger: [
    "AWOOO! Them hard hats opened the gate — FREE SPINS!",
    "WELL BUST MY BRITCHES — IT'S THE BONUS, PARTNER!",
    "THE PIGS ARE BUILDIN' AND WE'RE COMIN' FOR 'EM!",
    "SIX HATS! TIME TO HUFF AND PUFF FER REAL!",
    "BONUS ROUND, PARTNER — THE HUNT IS ON!",
    "YEEHAW! THE BIG BAD BONUS DONE TRIGGERED!",
    "RING THE BELL — FREE SPINS AT THE PIG FARM!",
    "I BEEN WAITIN' ALL DAY FER THIS — BONUS TIME!",
    "GRAB YER HAT — WE'RE GOIN' HOUSE TO HOUSE!",
    "THE WHOLE FOREST HEARD THAT ONE! BONUS, BABY!",
    "HOO-WEE! Now the real huffin' begins!",
  ],
  freeSpin: [
    "Another free one — build them houses, piggies!",
    "Free spin a-comin' — more straw to blow down!",
    "On the house, partner — just how I like it!",
    "Stack them frames up — I'll huff 'em all down!",
    "Come on, hard hats — show yer faces!",
    "Free spin! Let's fatten up that prize!",
    "More bricks, more loot — keep 'em comin'!",
    "Round on the house — yeehaw!",
    "Let's see them pigs work fer MY supper!",
    "Another crack at the henhouse — free!",
    "Spin's on me, partner — well, on the pigs!",
  ],
  frameUpgrade: [
    "A hat! That house just got a sight bigger!",
    "Buildin' up, partner — more to blow down later!",
    "Ooo, them walls are risin'! Good, GOOD!",
    "Upgrade! The bigger they are, the harder I huff!",
    "Another hat on the pile — keep stackin'!",
    "Them pigs are workin' hard fer my benefit!",
    "Walls goin' up means winnins goin' up!",
  ],
  brickAchieved: [
    "A BRICK HOUSE! Oh, that's the GOOD eatin' right there!",
    "FULL BRICK, partner — top dollar inside!",
    "Them pigs built it solid — and I built it RICH!",
    "Brick by brick, that's a fortune waitin'!",
    "Solid as a mountain — and twice as valuable!",
    "Now THAT house has somethin' worth blowin' fer!",
  ],
  wolfReveal: [
    "Step aside — the BIG BAD WOLF is here!",
    "Heh heh... I'll huff, and I'll puff, partner!",
    "Time to do what a wolf does best!",
    "Knock knock, little pigs — guess who?",
    "The wind's got teeth now, partner!",
    "Here comes the huffin', here comes the puffin'!",
    "Awooo! Let me at them houses!",
  ],
  wolfStraw: [
    "HUFF! And the straw goes flyin'! Easy pickins!",
    "One puff and that straw house is GONE!",
    "Ha! Straw don't stand a chance against me!",
    "Down she goes — straw all over the prairie!",
    "Barely a breath and POOF — straw's history!",
  ],
  wolfStick: [
    "PUFF! Them sticks are scatterin' ever' which way!",
    "A bigger blow and TIMBER — sticks down!",
    "Heh, had to put a little muscle in that one!",
    "Stick house crumbles like a dry biscuit!",
    "Whoosh! Kindlin' fer my campfire now!",
  ],
  wolfBrick: [
    "HUFF AND PUFF — I'm givin' her all I got!",
    "Them bricks are stubborn... but the PRIZE inside, ooo-wee!",
    "Not by the hair of my chinny-chin-chin — but LOOK at that payout!",
    "The brick house stands... and pays a wolf's ransom!",
    "Couldn't blow it down, but I'll take the treasure!",
    "Solid bricks, solid GOLD, partner!",
  ],
  mansionJackpot: [
    "MANSION JACKPOT! WELL I'LL BE A HORNSWOGGLED WOLF!",
    "THREE MANSIONS! THE WHOLE PIG EMPIRE IS OURS!",
    "JACKPOT! JACKPOT! AWOOOO! THE BIG ONE, PARTNER!",
    "I COULDN'T BLOW 'EM DOWN, SO I'M CASHIN' 'EM IN!",
    "THE GRANDEST HAUL IN ALL THE FOREST! YEEHAW!",
  ],
  miniJackpot: [
    "JACKPOT, partner! Treasure in the chimney!",
    "Well lookie — a pot o' gold in that house!",
    "Mini jackpot! Them pigs were hidin' loot!",
    "Found the stash, partner! Heh heh heh!",
  ],
  retrigger: [
    "MORE free spins?! Don't mind if I DO!",
    "Retrigger! The hunt keeps on goin'!",
    "Three more hats — extra spins on the house!",
    "Awooo! We ain't done feastin' yet!",
    "The bonus keeps givin' like a generous pig!",
  ],
  bonusComplete: [
    "And that's a wrap, partner — fine huntin' today!",
    "Bonus done — the pigs live to build another day!",
    "Belly's full, den's richer — what a round!",
    "We blew through them houses good, partner!",
    "Last puff's been puffed — let's count the loot!",
  ],
  idle: [
    "Reels are quiet... too quiet fer my likin', partner.",
    "I can smell them three little pigs from here...",
    "Go on, give 'er a spin — the wolf gets restless!",
    "Just me, the moon, and a hankerin' fer bacon.",
    "Press that button, partner — daylight's burnin'!",
    "I hear them pigs hammerin' away... let 'em build.",
    "A wolf waits... but not too patient-like, ya hear?",
    "Tumbleweed just rolled by. That's your cue, partner.",
    "The henhouse ain't gonna raid itself, ya know.",
    "I been sharpenin' my huffin' fer the next round.",
    "Quiet as a church mouse out here — spin somethin'!",
    "My whiskers are gettin' dusty. Let's ride!",
    "Them reels are just sittin' there, tauntin' me.",
    "Story goes the wolf always gets his supper. Eventually.",
    "Take yer time, partner. The pigs sure are.",
    "I could go fer a spin... and a snack.",
    "Wind's pickin' up. Perfect weather fer huffin'.",
    "Fortune favors the hungry — and I'm STARVIN'.",
    "Out here narratin' to the cactus again, I see.",
    "Even the moon's waitin' on ya, partner.",
    "A good wolf knows patience. A great one knows when to POUNCE.",
    "Reckon them pigs think they're safe. Reckon they're wrong.",
    "Spin the reels 'fore I start chewin' the furniture!",
    "Long as there's pigs to chase, ol' Wolf's stickin' around.",
  ],
  firstSpin: [
    "Well howdy, partner — welcome to BIG BAD WOLF! Let's hunt!",
    "Saddle up! First spin of the day — make it a good 'un!",
    "The wolf is hungry and the pigs are nervous — here we GO!",
    "Welcome to my neck o' the woods, partner! First spin's a-comin'!",
  ],
  lowBalance: [
    "Careful now, partner — the purse is gettin' light.",
    "We're runnin' lean, like a wolf in winter...",
    "Balance is thin as straw. Need a big huff soon!",
    "Pockets near empty, partner — time fer a comeback!",
    "Low on coin, but a wolf's luck can turn quick!",
  ],
  betUp: [
    "Raisin' the stakes! I LIKE yer appetite, partner!",
    "Bigger bet, bigger bacon! Now yer talkin'!",
    "Ooo-wee, goin' for the whole hog, are ya?",
    "More on the line — that's the wolf spirit!",
  ],
  betDown: [
    "Easin' off a touch — smart, partner, smart.",
    "Playin' it cagey. A wise wolf does the same.",
    "Smaller bet, longer hunt. I respect it.",
    "Dialin' it back to live and huff another day.",
  ],
  postWin: [
    "Look at them coins pile up — purty as a sunset!",
    "Keep 'em comin', partner — fill the den!",
    "That counter's climbin' like a cat up a tree!",
    "Sweetest sound there is — coins and squealin' pigs!",
    "I could watch this all dang day, partner!",
    "The loot just keeps a-rollin' in! Yeehaw!",
    "My belly AND my coin purse are happy now!",
    "That's a payout worth howlin' over! Awooo!",
  ],
  winStreak: [
    "Another'n?! We're on a TEAR, partner!",
    "Back to back — this machine's runnin' scared!",
    "Hotter'n a brandin' iron! Keep it up!",
    "The pigs can't build fast enough fer us!",
    "Win after win — the wolf is on the PROWL!",
    "Don't nobody touch nothin' — we're blazin'!",
    "Three in a row! I'm howlin' at the moon!",
    "This here's a winnin' streak fer the ages!",
    "Stampede o' luck, partner — ride it!",
  ],
  noFunds: [
    "Aw, partner — the purse is plumb empty.",
    "Den's bare and the pockets are dry. Reload to ride!",
    "That's all she wrote — outta coin, partner.",
    "Even a big bad wolf runs outta supper sometime.",
    "Empty-handed, but full of stories! Refill to hunt again!",
  ],
};
