/**
 * @module phrases
 * @description Every line the narrator can say, in the voice of the BIG BAD WOLF —
 * a gruff cowboy wolf straight out of the Three Little Pigs. Grouped by game event.
 *
 * This is the SINGLE source of truth for the narrator script. It's imported by:
 *   • narrator.js      – picks a random line per event and plays the matching MP3
 *   • tools/voice.js   – generates the MP3s from ElevenLabs (one file per line)
 *
 * Files live at  assets/audio/narrator/<category>_<index>.mp3  where <index> is the
 * line's position in its array. So the array order here defines which file is which —
 * if you re-order or change counts, re-run `node tools/voice.js all <voiceId>`.
 */
'use strict';

export const PHRASES = {
  spin: [
    "Alright partner, let's give them reels a spin!",
    "Heeere we go now — round and round she goes!",
    "Spin 'em up, and let's see what the wind blows in!",
    "Ooo-wee! Let's rattle them reels, partner!",
    "Come on now, daddy needs a new pair o' boots!",
    "Awooo! Let 'er rip!",
    "Let's huff up a storm and spin this thing!",
    "Round the reels go — where they stop, heh, only I know!",
    "Crank 'er up, partner — I got a hankerin' for a win!",
    "Spinnin' faster'n a tumbleweed in a twister!",
    "Let's see if them pigs left us anything good!",
    "Hold onto your hat — here she spins!",
    "I feel a lucky wind a-blowin', partner!",
    "Saddle up! These reels are about to ride!",
    "One good huff oughta get these reels movin'!",
    "Come on, sugar — show ol' Wolf somethin' sweet!",
    "Reels a-turnin', and my belly's a-rumblin'!",
    "Yeehaw! Down the trail we go!",
    "Spin it like you mean it, partner!",
    "Let's blow the doors off this one!",
    "Here comes the big bad spin, little piggies!",
    "My whiskers are twitchin' — that means money!",
    "Let's kick up some dust on these here reels!",
    "Come on now, line 'em up like ducks in a row!",
    "Easy does it... and... SPIN!",
    "Wind's at our back, partner — let 'er fly!",
    "Give 'er a whirl! Fortune favors the hungry!",
    "Round we go — I can almost taste them winnins!",
  ],
  smallWin: [
    "Well lookie there — a lil' nibble!",
    "Heh, ain't much, but a wolf don't turn down a snack!",
    "A few coins for the den! I'll take it!",
    "That there's an appetizer, partner!",
    "Small bite, but tasty all the same!",
    "Cha-ching — that's some kibble money!",
    "Not a feast, but it'll hold me over!",
    "A lil' somethin' for the chinny-chin-chin!",
    "Coins in the coat, partner — every bit counts!",
    "Heh heh, them pigs dropped a few on the way out!",
    "A modest haul, but ol' Wolf is patient!",
    "That'll buy me a new neckerchief at least!",
    "Small win, big appetite — keep 'em comin'!",
    "Pocket change, but my pockets run deep!",
    "A nibble here, a nibble there — adds up, partner!",
    "Yeehaw, a little drizzle 'fore the storm!",
    "I've et smaller, partner — we'll take it!",
    "Couple coins jingle-jangle — music to my ears!",
  ],
  mediumWin: [
    "Now we're cookin' with bacon grease!",
    "Ooo-wee! That's a proper meal right there!",
    "Heh heh HEH! The pigs are payin' up!",
    "Now THAT'S a haul worth howlin' about! Awooo!",
    "Look at them coins runnin' like scared piggies!",
    "That's the good stuff, partner — sink yer teeth in!",
    "A solid bite outta this here game!",
    "Yeehaw! The wind's blowin' our way!",
    "That'll fill the den AND the belly!",
    "Mighty fine payout, partner — mighty fine!",
    "Them reels finally came to their senses!",
    "Oh, I'm lickin' my chops over this one!",
    "Now we're talkin' real wolf money!",
    "That's a wagon-load of coins, partner!",
    "Huff, puff, and PAYDAY! Beautiful!",
    "The pigs are squealin' and I'm grinnin'!",
    "A fine cut of winnins, served up hot!",
    "Ringin' the dinner bell on that one!",
  ],
  bigWin: [
    "AWOOOOO! Now THAT is a feast, partner!",
    "WELL SLAP MY TAIL AND CALL ME LUCKY!",
    "HOO-WEE! The whole dang henhouse just paid out!",
    "I HUFFED, I PUFFED, AND I BLEW THE BANK WIDE OPEN!",
    "GREAT GALLOPIN' GOLD! LOOK AT THEM COINS!",
    "NOT BY THE HAIR — THIS HERE'S A MONSTER, PARTNER!",
    "YEEEEHAW! BIGGEST HAUL THIS SIDE O' THE FOREST!",
    "THEM PIGS DONE LEFT THE WHOLE TREASURE BEHIND!",
    "I'M HOWLIN' AT THE MOON OVER THIS ONE! AWOOO!",
    "STAMPEDE OF COINS, PARTNER — GET OUTTA THE WAY!",
    "MY CHINNY-CHIN-CHIN IS TREMBLIN' WITH JOY!",
    "BLOW ME DOWN — THAT'S A FORTUNE!",
    "HOT DIGGITY WOLF, WE STRUCK IT RICH!",
    "RING THE DINNER BELL — IT'S A BANQUET!",
    "I AIN'T NEVER SEEN SO MANY COINS IN ALL MY DAYS!",
    "THE BIG BAD WOLF HITS THE BIG BAD JACKPOT!",
    "GRAB A BUCKET, PARTNER — IT'S RAININ' GOLD!",
    "MY WHISKERS 'BOUT FELL OFF — WHAT A WIN!",
    "WOOOO! TELL THE WHOLE FOREST WE DONE IT!",
    "THIS HERE'S A WIN FER THE STORYBOOKS!",
  ],
  loss: [
    "Aw, shucks — empty as a pig pen at suppertime.",
    "Nothin' but tumbleweeds on that one, partner.",
    "Hmph. Them pigs got away clean that round.",
    "Dry as the desert. Shake it off, partner.",
    "No bacon this time. We huff again!",
    "Ah well — even a wolf misses a meal now and then.",
    "The wind died down on that one. Reload them lungs!",
    "Nothin' in the henhouse. Onward!",
    "Them reels are playin' coy. I like a challenge.",
    "Missed 'em by a whisker. We'll get 'em next time.",
    "No coins, no problem — a wolf is patient.",
    "That house didn't budge. Bigger huff next round!",
    "Empty-pawed, but not for long, partner.",
    "Heh, them pigs think they're safe. Cute.",
    "Dust in the wind. Let's spin her again.",
    "A swing and a miss. Sharpen them claws!",
    "Not a crumb that time. My belly grumbles on.",
    "Quiet round. Calm 'fore the big bad storm.",
  ],
  lossStreak: [
    "Come on now — them pigs can't hide forever!",
    "Dang it all, this dry spell's testin' my patience!",
    "A wolf's gotta eat! Throw me a bone here!",
    "Been a long, dusty trail without a meal...",
    "I've huffed till I'm blue — somethin's gotta give!",
    "Them three pigs are gettin' cocky. Won't last!",
    "Every drought ends in a downpour, partner. Hold fast!",
    "I can smell a big win comin' over the ridge!",
    "These reels OWE me — and a wolf always collects!",
    "Lean times, partner — but the wolf endures!",
    "I've gone hungrier'n this and still ate good!",
    "The bricks are holdin' for now. Keep huffin'!",
    "Patience, partner. Even the moon takes its time.",
    "My luck's 'bout to turn like the prairie wind!",
    "Storm's been brewin' — any spin now she breaks!",
    "Keep the faith — the big bad payday's comin'!",
  ],
  nearMiss: [
    "Ooo! Nearly had them pigs by the tail!",
    "One whisker away! ONE! Dadgummit!",
    "So close I could smell the bacon fryin'!",
    "Argh — that house near 'bout came down!",
    "Them pigs slipped out the back door, partner!",
    "A hair! Not by the hair of my chinny-chin-chin!",
    "Teasin' me, are ya? Them reels are cruel!",
    "I had 'em cornered and they wriggled free!",
    "Almost blew it down! One more gust!",
    "My chops were waterin' — and POOF, gone!",
    "Right there! It was RIGHT there, partner!",
    "Close enough to feel the wind change!",
  ],
  extremeAnticipation: [
    "Ooooh! Five hats! One more and we blow the house down!",
    "Hold yer breath partner... we just need one more!",
    "Five hats! Come on, number six! Awooo!",
    "One more hat and it's bonus time! Let's go!",
    "The anticipation is killin' me! Drop that hat!"
  ],
  bonusTrigger: [
    "AWOOO! Them hard hats opened the gate — FREE SPINS!",
    "WELL BUST MY BRITCHES — IT'S THE BONUS, PARTNER!",
    "THE PIGS ARE BUILDIN' AND WE'RE COMIN' FOR 'EM!",
    "SIX HATS! TIME TO HUFF AND PUFF FER REAL!",
    "BONUS ROUND, PARTNER — THE HUNT IS ON!",
    "YEEHAW! THE BIG BAD BONUS DONE TRIGGERED!",
    "RING THE BELL — FREE SPINS AT THE PIG FARM!",
    "I BEEN WAITIN' ALL DAY FER THIS — BONUS TIME!",
    "GRAB YER HAT — WE'RE GOIN' HOUSE TO HOUSE!",
    "THE WHOLE FOREST HEARD THAT ONE! BONUS, BABY!",
    "HOO-WEE! Now the real huffin' begins!",
  ],
  freeSpin: [
    "Another free one — build them houses, piggies!",
    "Free spin a-comin' — more straw to blow down!",
    "On the house, partner — just how I like it!",
    "Stack them frames up — I'll huff 'em all down!",
    "Come on, hard hats — show yer faces!",
    "Free spin! Let's fatten up that prize!",
    "More bricks, more loot — keep 'em comin'!",
    "Round on the house — yeehaw!",
    "Let's see them pigs work fer MY supper!",
    "Another crack at the henhouse — free!",
    "Spin's on me, partner — well, on the pigs!",
  ],
  frameUpgrade: [
    "A hat! That house just got a sight bigger!",
    "Buildin' up, partner — more to blow down later!",
    "Ooo, them walls are risin'! Good, GOOD!",
    "Upgrade! The bigger they are, the harder I huff!",
    "Another hat on the pile — keep stackin'!",
    "Them pigs are workin' hard fer my benefit!",
    "Walls goin' up means winnins goin' up!",
  ],
  brickAchieved: [
    "A BRICK HOUSE! Oh, that's the GOOD eatin' right there!",
    "FULL BRICK, partner — top dollar inside!",
    "Them pigs built it solid — and I built it RICH!",
    "Brick by brick, that's a fortune waitin'!",
    "Solid as a mountain — and twice as valuable!",
    "Now THAT house has somethin' worth blowin' fer!",
  ],
  wolfReveal: [
    "Step aside — the BIG BAD WOLF is here!",
    "Heh heh... I'll huff, and I'll puff, partner!",
    "Time to do what a wolf does best!",
    "Knock knock, little pigs — guess who?",
    "The wind's got teeth now, partner!",
    "Here comes the huffin', here comes the puffin'!",
    "Awooo! Let me at them houses!",
  ],
  wolfStraw: [
    "HUFF! And the straw goes flyin'! Easy pickins!",
    "One puff and that straw house is GONE!",
    "Ha! Straw don't stand a chance against me!",
    "Down she goes — straw all over the prairie!",
    "Barely a breath and POOF — straw's history!",
  ],
  wolfStick: [
    "PUFF! Them sticks are scatterin' ever' which way!",
    "A bigger blow and TIMBER — sticks down!",
    "Heh, had to put a little muscle in that one!",
    "Stick house crumbles like a dry biscuit!",
    "Whoosh! Kindlin' fer my campfire now!",
  ],
  wolfBrick: [
    "HUFF AND PUFF — I'm givin' her all I got!",
    "Them bricks are stubborn... but the PRIZE inside, ooo-wee!",
    "Not by the hair of my chinny-chin-chin — but LOOK at that payout!",
    "The brick house stands... and pays a wolf's ransom!",
    "Couldn't blow it down, but I'll take the treasure!",
    "Solid bricks, solid GOLD, partner!",
  ],
  mansionJackpot: [
    "WANTED REWARD! WELL I'LL BE A HORNSWOGGLED WOLF!",
    "BOUNTY'S MINE! THE WHOLE PIG EMPIRE IS OURS!",
    "JACKPOT! JACKPOT! AWOOOO! THE BIG ONE, PARTNER!",
    "I COULDN'T BLOW 'EM DOWN, SO I'M CASHIN' 'EM IN!",
    "THE GRANDEST HAUL IN ALL THE FOREST! YEEHAW!",
  ],
  miniJackpot: [
    "JACKPOT, partner! Treasure in the chimney!",
    "Well lookie — a pot o' gold in that house!",
    "Mini jackpot! Them pigs were hidin' loot!",
    "Found the stash, partner! Heh heh heh!",
  ],
  retrigger: [
    "MORE free spins?! Don't mind if I DO!",
    "Retrigger! The hunt keeps on goin'!",
    "Three more hats — extra spins on the house!",
    "Awooo! We ain't done feastin' yet!",
    "The bonus keeps givin' like a generous pig!",
  ],
  bonusComplete: [
    "And that's a wrap, partner — fine huntin' today!",
    "Bonus done — the pigs live to build another day!",
    "Belly's full, den's richer — what a round!",
    "We blew through them houses good, partner!",
    "Last puff's been puffed — let's count the loot!",
  ],
  idle: [
    "Reels are quiet... too quiet fer my likin', partner.",
    "I can smell them three little pigs from here...",
    "Go on, give 'er a spin — the wolf gets restless!",
    "Just me, the moon, and a hankerin' fer bacon.",
    "Press that button, partner — daylight's burnin'!",
    "I hear them pigs hammerin' away... let 'em build.",
    "A wolf waits... but not too patient-like, ya hear?",
    "Tumbleweed just rolled by. That's your cue, partner.",
    "The henhouse ain't gonna raid itself, ya know.",
    "I been sharpenin' my huffin' fer the next round.",
    "Quiet as a church mouse out here — spin somethin'!",
    "My whiskers are gettin' dusty. Let's ride!",
    "Them reels are just sittin' there, tauntin' me.",
    "Story goes the wolf always gets his supper. Eventually.",
    "Take yer time, partner. The pigs sure are.",
    "I could go fer a spin... and a snack.",
    "Wind's pickin' up. Perfect weather fer huffin'.",
    "Fortune favors the hungry — and I'm STARVIN'.",
    "Out here narratin' to the cactus again, I see.",
    "Even the moon's waitin' on ya, partner.",
    "A good wolf knows patience. A great one knows when to POUNCE.",
    "Reckon them pigs think they're safe. Reckon they're wrong.",
    "Spin the reels 'fore I start chewin' the furniture!",
    "Long as there's pigs to chase, ol' Wolf's stickin' around.",
  ],
  firstSpin: [
    "Well howdy, partner — welcome to BIG BAD WOLF! Let's hunt!",
    "Saddle up! First spin of the day — make it a good 'un!",
    "The wolf is hungry and the pigs are nervous — here we GO!",
    "Welcome to my neck o' the woods, partner! First spin's a-comin'!",
  ],
  lowBalance: [
    "Careful now, partner — the purse is gettin' light.",
    "We're runnin' lean, like a wolf in winter...",
    "Balance is thin as straw. Need a big huff soon!",
    "Pockets near empty, partner — time fer a comeback!",
    "Low on coin, but a wolf's luck can turn quick!",
  ],
  betUp: [
    "Raisin' the stakes! I LIKE yer appetite, partner!",
    "Bigger bet, bigger bacon! Now yer talkin'!",
    "Ooo-wee, goin' for the whole hog, are ya?",
    "More on the line — that's the wolf spirit!",
  ],
  betDown: [
    "Easin' off a touch — smart, partner, smart.",
    "Playin' it cagey. A wise wolf does the same.",
    "Smaller bet, longer hunt. I respect it.",
    "Dialin' it back to live and huff another day.",
  ],
  postWin: [
    "Look at them coins pile up — purty as a sunset!",
    "Keep 'em comin', partner — fill the den!",
    "That counter's climbin' like a cat up a tree!",
    "Sweetest sound there is — coins and squealin' pigs!",
    "I could watch this all dang day, partner!",
    "The loot just keeps a-rollin' in! Yeehaw!",
    "My belly AND my coin purse are happy now!",
    "That's a payout worth howlin' over! Awooo!",
  ],
  winStreak: [
    "Another'n?! We're on a TEAR, partner!",
    "Back to back — this machine's runnin' scared!",
    "Hotter'n a brandin' iron! Keep it up!",
    "The pigs can't build fast enough fer us!",
    "Win after win — the wolf is on the PROWL!",
    "Don't nobody touch nothin' — we're blazin'!",
    "Three in a row! I'm howlin' at the moon!",
    "This here's a winnin' streak fer the ages!",
    "Stampede o' luck, partner — ride it!",
  ],
  noFunds: [
    "Aw, partner — the purse is plumb empty.",
    "Den's bare and the pockets are dry. Reload to ride!",
    "That's all she wrote — outta coin, partner.",
    "Even a big bad wolf runs outta supper sometime.",
    "Empty-handed, but full of stories! Refill to hunt again!",
  ],

  /* ═══════════════════════════════════════════════════════════════════════
     CONTEXTUAL POOLS — selected by the Wolf VO manager based on real game
     state (visible symbols, win tier, streaks, idle, bonus mode, expansions).
     Symbol callouts are mapped to what the player actually SEES:
       shot glass = 'toolbox'   horseshoe = 'pig-suit'/'pig-contractor'
       wolf wild  = 'wild'       hard hats  = the bonus-building 'hat-*'.
     Responsible play: no "you're due", no pressure, no guaranteed wins.
  ═══════════════════════════════════════════════════════════════════════ */

  // Base-game saloon ambience (rare idle flavor)
  ambient: [
    "Place yer bet, partner. The wolf's watchin' the door.",
    "This saloon's got three rules: spin fair, count fast, and don't build with straw.",
    "I smell coin dust, hoof tracks, and just enough trouble to keep me interested.",
    "Round here, even the tumbleweeds know when the reels are warm.",
    "Pull up a stool. Ol' Wolf's got eyes on the whole saloon.",
    "The bar's open, the reels are restless, and I'm in a generous mood.",
    "Careful now. This place smiles before it bites.",
    "Dusty reels, shiny coins, nervous little pigs upstairs. My kind o' evenin'.",
    "The piano stopped playin'. Usually means somethin' expensive is comin'.",
    "I've blown down straw, sticks, and bad alibis. Let's see what these reels are made of.",
    "Quiet saloon, restless reels. Dangerous little combination.",
    "Somewhere upstairs, a little pig just locked his door.",
  ],
  idleAfterWin: [
    "Admirin' the win? Can't blame ya. I'd frame it over the bar.",
    "That one had some bite. Take yer second, partner.",
    "Coins still smell warm from here.",
    "A haul like that makes the pigs peek through the curtains.",
    "Not a bad little pile. The saloon noticed.",
    "Sit with it. Good wins deserve a slow whiskey.",
  ],
  idleAfterLoss: [
    "No rush, partner. The saloon ain't runnin' off.",
    "Quiet result, loud possibilities.",
    "Dust it off. Take yer time.",
    "Even wolves miss a hoofprint now and then.",
    "Take a breath. The reels'll keep.",
    "Easy does it. No trail's in a hurry.",
  ],
  coldStreak: [
    "Dry patch. Keep yer head, partner.",
    "Dusty trail right now. No shame in slowin' down.",
    "Reels are playin' hard to get. That's their bad habit.",
    "Cold wind through the saloon. Happens to the best boots.",
    "No need to chase every tumbleweed.",
    "Quiet stretch. Stretch yer legs if ya like.",
  ],
  twoWinStreak: [
    "That's two in a row. Somebody bolt the pig pen.",
    "Back to back? The chimney's startin' to rattle.",
    "Two wins walkin' side by side.",
    "The reels are startin' to recognize ya.",
    "Two knocks at the same door.",
    "Second win, and the wolf is listenin'.",
    "That's two. Even the horseshoe blinked.",
    "A little streak just found its boots.",
  ],
  threeWinStreak: [
    "Three runnin'. Straw, sticks, bricks — don't matter. I'm at the door.",
    "Three in a row. Now the pigs are holdin' a meetin'.",
    "That streak's got teeth now.",
    "That ain't luck knockin'. That's luck kickin'.",
    "Three bites in a row. Clean work.",
    "Now we've got a proper trail.",
    "The reels are warmin' their paws.",
    "That streak just ordered a drink.",
  ],
  hotStreak: [
    "Win streak's got spurs on it.",
    "This run's huffin' hotter than a desert forge.",
    "The saloon's leanin' in now.",
    "That trail's turnin' into a stampede.",
    "Keep this up and the pigs'll file a noise complaint.",
    "Now the reels are dancin' on the bar.",
    "Hot run, cool head.",
    "The whole room smells like coin dust.",
  ],
  streakEnded: [
    "Streak took a bow. Even wolves tip their hat.",
    "Trail cooled off. Happens to the best boots.",
    "That run had style while it lasted.",
    "Dust settles after every stampede.",
    "Streak's done, but the saloon remembers.",
  ],
  anticipation: [
    "Hold up. Last reel's draggin' its boots.",
    "Easy now. That reel's makin' a meal of it.",
    "Don't blink. This last reel's got drama in its pockets.",
    "Somethin's knockin' behind that reel.",
    "I hear floorboards creakin'.",
    "Come on now. Show yer teeth.",
    "The dust just stopped movin'.",
    "Careful. This is where the saloon holds its breath.",
    "Last reel's got a secret. Let's see if it talks.",
    "One more step, little piggy.",
    "That reel's stallin' like a pig at rent time.",
    "The saloon went quiet. That's luck or a sneaky pig.",
  ],
  expandingReels: [
    "Walls are stretchin'. Somebody built this place with wolf-sized plans.",
    "Reels are openin' up. More room for trouble.",
    "That's an expansion, partner. Bigger floor, bigger dance.",
    "The saloon just kicked out a wall.",
    "More reels, more room to huff.",
    "Look at that — the reels grew teeth.",
    "That wall came down easier than straw.",
    "The place is stretchin' like it heard my name.",
    "Bigger reels, bigger shadow.",
    "Now we've got elbow room.",
    "Wolf wild on the floorboards. Respect it.",
    "When the wolf goes wild, the saloon checks the locks.",
  ],
  bonusEnter: [
    "Bonus round, partner. Bigger chances, bigger teeth.",
    "Keep yer hat low. The bonus can kick harder than a mule.",
    "This is the back room, where the real coin smoke curls.",
    "Don't count the bricks yet. Let the bonus breathe.",
    "Now we're in bonus country. Pigs lock the windows out here.",
    "This is where straw houses become cautionary tales.",
    "Step inside. The floorboards know my name.",
    "Bonus round. Same wolf, bigger shadow.",
    "The bonus is open, and I brought lungs.",
    "Now the saloon gets honest.",
  ],
  bonusSpin: [
    "Bonus reels turnin'. That sound never gets old.",
    "Every bonus spin's a fresh bootprint.",
    "Let's see what the back room pays.",
    "The pigs are countin' bricks. I'm countin' chances.",
    "This bonus still has dust to kick up.",
    "Keep one eye on the wilds.",
    "Let it breathe. Let it bite.",
    "Bonus country's got sharp teeth.",
    "More room for the wolf in here.",
    "That reel's got back-room manners.",
  ],
  bonusWin: [
    "Now that's a bonus with bite.",
    "Piggy bank just heard hoofbeats.",
    "That one rattled the rafters.",
    "Coins on the floor, smoke in the air.",
    "The back room pays when it's in the mood.",
    "That hit had spurs.",
    "I felt that one in my whiskers.",
    "Now we're cookin' with wolf breath.",
    "Bonus teeth, right there.",
    "That win kicked the saloon doors off.",
  ],
  bonusBigWin: [
    "That's the kind o' bonus that makes brick houses nervous.",
    "The pigs just moved to a safer county.",
    "That win didn't knock. It kicked the door clean in.",
    "I'd huff for that one twice.",
    "Somebody check the roof. I think it lifted.",
    "Now the saloon's payin' attention.",
    "A bonus like that leaves claw marks.",
    "That pile's got its own shadow.",
  ],
  bonusEnd: [
    "Bonus is over. Check yer pockets for scorch marks.",
    "Back to the bar. I left claw marks on that bonus.",
    "The back room closes, but the wolf remembers.",
    "That bonus took a bow.",
    "Doors shut, dust settles, coins tell the story.",
    "That was a ride through wolf country.",
    "Back to base game. Same saloon, fresh trouble.",
    "The bonus is done. The pigs can stop whisperin'.",
    "Put that one in the ledger.",
    "Bonus trail ends here, partner.",
  ],
  symShotGlass: [
    "Shot glass on the rail. Tiny cup, big attitude.",
    "I see the shot glass. Bartender's pretendin' not to.",
    "That shot glass looks guilty.",
    "Glass on the reels. Somebody's buyin' trouble.",
    "That little glass has seen things.",
    "Shot glass showin'. Saloon's in session.",
    "Careful with that glass. It bites back.",
    "That glass is small, but it walks loud.",
  ],
  symShotGlassMulti: [
    "More than one shot glass? Now the piano's nervous.",
    "Two glasses showin'. Trouble's pourin'.",
    "That's a rowdy little shelf o' glass.",
    "The bartender just looked over.",
    "Glasses stackin' up. The night got interestin'.",
  ],
  symHorseshoe: [
    "Lucky horseshoe showin'. Let's see if it remembers its job.",
    "There's that horseshoe, shinin' like it owes ya money.",
    "Horseshoe on deck. Superstition just put on boots.",
    "That horseshoe's got a smug little shine.",
    "Iron luck on the reels.",
    "A horseshoe in the window. That'll make a wolf curious.",
    "That horseshoe better not be all hat and no cattle.",
    "Horseshoe flashin'. The saloon noticed.",
  ],
  symHorseshoeMulti: [
    "Two horseshoes? Now luck's wearin' both boots.",
    "That's a lot o' lucky iron.",
    "Horseshoes stackin' up. The floorboards feel fortunate.",
    "Three horseshoes? Even I'd call that suspicious.",
    "Luck just walked in wearin' spurs.",
  ],
  symHats: [
    "Hard hats pilin' up. Six of 'em opens the back room.",
    "Look at them hard hats. The bonus is sniffin' around.",
    "Hats on the reels. The pigs put on their helmets.",
    "Construction crew's clockin' in. Hard hats everywhere.",
    "Them hard hats mean business when they crowd in.",
    "I count hard hats like I count piggies — hungrily.",
    "Hats gatherin'. Six opens the bonus doors.",
    "That's a brave little crew of hard hats.",
  ],
  menuReturn: [
    "Back from the paperwork? Good. The reels missed us.",
    "Rules read, boots dusted, wolf ready.",
    "Paytable's got the map. I've got the teeth.",
    "Settings settled. Saloon's still standin'.",
    "Welcome back. The pigs got nervous while ya were gone.",
    "Took yer time in there. The whiskey's still cold.",
  ],
  // Friendly teasing of the "other" huff-and-puff act — OFF by default in the manager.
  roasts: [
    "I heard some other puff act needed a whole machine to blow a house down. Cute.",
    "Huff and more puff? Please. Round here, one good breath gets the job done.",
    "Some wolves need fireworks. I just need a door hinge and bad construction.",
    "Tell that other puff parlor the bricks still look nervous.",
    "There's puff, then there's performance. Mine comes with teeth.",
    "Some games huff. Some games puff. This one bites.",
    "I don't need a fancy sign. I got lungs and a grudge.",
    "Other wolves make noise. I make renovations.",
    "More puff? Partner, I brought plenty.",
    "I've seen puff acts with less bite than a saloon napkin.",
  ],
  // Click the "BIG BAD WOLF SALOON" sign → the wolf brags about his joint.
  saloonHeader: [
    "Big Bad Wolf Saloon. My name's on the door 'cause I huffed down the last three.",
    "Welcome to my saloon, partner. Finest whiskey, worst-built houses in the territory.",
    "This here's the Big Bad Wolf Saloon. Pigs drink free — if they can outrun the tab.",
    "Every board in this place, I blew in from somewhere else.",
    "Big Bad Wolf Saloon, where the piano's honest and the pigs ain't.",
    "Built it myself. Well — I huffed, the pigs built, then I moved in.",
    "My saloon, my rules, my reels. Pull up a stool.",
    "They named it after me. Only fair — I'm the one with the lungs.",
    "No straw, no sticks in this saloon. Just good solid trouble.",
    "Finest saloon west of the brick house. Only one, too. Funny how that works.",
    "Step careful, partner. This saloon bites back, and so do I.",
  ],
  // Click the "Vegas Low Roller Approved" medallion → a friendly nod to VLR.
  vlrMedallion: [
    "Ah, Vegas Low Roller... I know him. Mighty fine YouTube channel.",
    "Vegas Low Roller approved, partner. That fella knows his slots.",
    "That's the Vegas Low Roller seal. Tell him the wolf says howdy.",
    "Vegas Low Roller — a low roller with a big heart. Good company to keep.",
  ],
  // Click the sheriff's star badge → the wolf claims the law.
  sheriffBadge: [
    "Careful, partner. That's the Sheriff's badge, and there is only one Sheriff in this town. That's me, Big Bad Wolf.",
    "That star's the Sheriff's badge. Round here, the law's got fur and a temper.",
    "Sheriff's badge, partner. I pinned it on myself. Nobody argued twice.",
    "Easy with that badge. The last fella who wore it... well, the pigs don't ask about him.",
  ],
  // Mouse hovers over SPIN for 3+ seconds without clicking → the wolf razzes 'em.
  spinHover: [
    "You gonna click it? Or just stare at it all day?",
    "That button ain't gonna press itself, partner.",
    "Go on, push it. It don't bite — that's my job.",
    "Starin' contest with the spin button? Bold strategy.",
    "Push it, partner. The reels are gettin' lonely.",
    "I've seen molasses move quicker than that trigger finger.",
    "It's shiny, I know. But it's prettier when it's spinnin'.",
    "You hoverin' or proposin'? Either way, do somethin'.",
    "Quit pettin' that button and give it a spin.",
    "Your hand's right there. The button's right there. You do the math.",
    "Take yer time. The pigs ain't goin' anywhere... probably.",
    "Any day now, partner. The whiskey's gettin' warm.",
  ],
  // Opening the BUY BONUS confirmation
  buyBonus: [
    "Buyin' yer way into the back room? Bold. I respect bold.",
    "Skippin' the line straight to the bonus, eh? Big spender.",
    "Payin' to kick the doors open? That's the spirit, partner.",
    "Why wait for the bonus when ya can drag it in by the collar?",
    "Cash on the bar for a shortcut to trouble. I like yer style.",
    "Buyin' the back room. Now that's a wolf-sized decision.",
    "Straight to the bonus, no dilly-dallyin'. My kind of partner.",
    "The pigs hate this option. That's how I know it's a good one.",
  ],
  // Bet raised to the maximum level
  maxBet: [
    "Max bet! Now yer huntin' like a real wolf.",
    "All the chips on the table — I LIKE it, partner.",
    "Bettin' the whole henhouse, are we? Bold.",
    "Max stakes. The pigs just got a lot more nervous.",
    "Now THAT'S an appetite. Top of the bettin' line.",
    "Goin' for the whole hog. Respect.",
    "Maxed 'er out. No straw houses for big spenders.",
    "Top dollar, partner. The saloon's payin' attention now.",
  ],
  // Idling while sitting on a big balance
  richIdle: [
    "Sittin' on a fat stack and starin' at the wall? Livin' the dream, partner.",
    "That's a healthy pile o' coin. Whiskey's on you tonight.",
    "Look at all that loot. Even the pigs are impressed.",
    "Big balance, calm hands. That's how a wolf does it.",
    "That pile's got its own gravity, partner.",
    "Coin like that, ya could buy yer own saloon. Oh wait — I already did.",
    "Restin' on a mountain of money. Can't say I blame ya.",
    "That's a stack worth guardin'. Good thing ya got a wolf for that.",
  ],

  /* ═══════ CLICK-A-SYMBOL JOKES — tap a reel symbol, the wolf riffs on it ═══════ */
  clickWolf: [
    "That handsome devil on the reel? Yeah, he gets it from me.",
    "Two wolves in one saloon? The pigs are officially doomed.",
    "Click me all ya want, partner. I don't break character.",
    "I'd recognize that snarl anywhere. It's my good side.",
    "That's my reel cousin. Still owes me twenty bucks.",
    "Careful pokin' the wolf. I bite back... affectionately.",
    "A wolf symbol. Finally, some good-lookin' competition.",
  ],
  clickBuzzard: [
    "That buzzard shows up when somethin's about to die. Usually a straw house.",
    "Ol' buzzard's just waitin' for the pigs to slip up. Patient fella.",
    "That bird's got worse manners than me, and that's sayin' somethin'.",
    "Buzzard pays the least 'cause he eats the leftovers. Even the reels know it.",
    "A buzzard. Circlin', circlin'... cheap date, though.",
    "That buzzard once tried to outwait a wolf. Lost. Badly.",
    "Don't mind the buzzard. He's just here for the scraps.",
  ],
  clickHat: [
    "Hard hat! Six of them little helmets and we kick the bonus doors open.",
    "Pigs wear hard hats thinkin' they'll save the house. Adorable.",
    "A hard hat. Safety first... right before I huff the whole thing down.",
    "Them pigs unionized. Now they got hard hats AND a mortgage.",
    "Collect six hard hats and the back room opens. I'll bring the lungs.",
    "A hard hat won't stop a wolf. But it's cute that they try.",
    "Construction crew's clockin' in. Six hats and the real fun starts.",
  ],
  clickHorseshoe: [
    "Lucky horseshoe! Stole it off a nervous pony. Don't tell.",
    "That horseshoe's upside down. All the luck's pourin' out. Tragic.",
    "Hang a horseshoe over the saloon door, they say. I just hang the pigs.",
    "Found a horseshoe once. The horse weren't usin' it... anymore.",
    "Iron luck on the reels. Shinier than the sheriff's badge — which is mine.",
    "That horseshoe's seen more miles than my boots, and that's a lot.",
    "A horseshoe. Good luck for you, bad luck for the pigs.",
  ],
  clickTornado: [
    "A tornado! That's just me sneezin', partner. Allergies.",
    "Twister on the reels. I huffed a little too hard last Tuesday.",
    "That tornado took a straw house clean to the next county. Saved me the trip.",
    "Don't worry 'bout the tornado. It's on my payroll.",
    "Nature's way of doin' my job for me. I respect the hustle.",
    "Pigs see a tornado. I see a coworker.",
    "That's a lot of wind, partner. And I'm the windiest thing in this saloon.",
  ],
  clickShotGlass: [
    "Shot glass! Bartender, leave the bottle. The wolf's thirsty.",
    "A little glass with a big attitude. Reminds me of the smallest pig.",
    "One shot for courage, partner. Two for a bad decision.",
    "That glass is empty. Somebody fix that immediately.",
    "Whiskey in a glass that small? That's just a tease.",
    "A shot glass on the reels. The night's officially gettin' interesting.",
    "Careful — one glass leads to ten, and ten leads to singin'.",
  ],
  clickRoyals: [
    "Playin' cards? In a saloon? Now somebody's definitely cheatin'.",
    "Ace, King, Queen... fancy letters for the low-payin' folks.",
    "Them royals don't pay much. Even the buzzard looks down on 'em.",
    "Last fella who played cards with me left in a real hurry.",
    "A face card. At least it's got a face — unlike that buzzard's personality.",
    "Them letters pay the least, partner. But they sure crowd in.",
    "Queen of hearts? In this town she runs the place. Don't cross her.",
  ],
  clickWild: [
    "That's the Wolf Wild — my finest work. Fills the whole reel, like my ego.",
    "The wild's all me, partner. When it lands, the saloon checks the locks.",
    "Click the wild all ya like. It's basically a portrait of yours truly.",
    "That snarl in the middle? Pure wolf. Accept no substitutes — 'cept that one.",
  ],

  // High-noon easter egg — the wolf narrates the standoff title card aloud.
  // Keep this line in sync with the #noon-card text in index.html.
  highNoon: [
    "Well, well... a stranger just moseyed into town on the stroke of twelve. But these here parts ain't big enough for the both of us — there's only one Big Bad Wolf in this saloon.",
  ],

  // High-noon STORYBOOK — read aloud after the standoff clip, one page at a time,
  // over the showdown music, then the gunshots. Each entry is ONE page: it is both
  // shown on screen (src/scenes/high-noon.js) and the text of its voiceover clip
  // (assets/audio/narrator/highNoonStory_<i>.mp3). Keep the two in sync.
  highNoonStory: [
    `For one very long moment, nobody moved.`,
    `A pig poked his head out from behind a rain barrel. "Can we maybe not do the huffing and puffing today?"`,
    `As the Sheriff in these parts, I gestured towards the pig and said, "Relax. He's already at Huff N' Even More Puff. There's nowhere left for him to go, end of line, partner, unless you really want more."`,
    `The town gasped. The sheriff wolf's ears twitched. A tumbleweed stopped rolling just to watch.`,
  ],
};
