/**
 * @module side-wolf
 * @description Gives the left-side SideWolf character a lively, dynamic feel.
 * He loops his default idle clip, then plays ONE randomly-chosen reaction
 * (dances, sniffs, fist-pump, tips his hat, …) once, and returns to idle —
 * forever. Every clip starts and ends in the same pose, so the swaps look
 * seamless.
 *
 * GAPLESS CROSSBUFFER — why two videos:
 * Swapping a single <video>'s src blanks the element while the browser loads
 * and decodes the next clip. On Safari (HEVC-alpha .mp4) that blank is a very
 * visible ~½s gap between loops. So we keep TWO stacked, identical video layers:
 * one plays while the OTHER silently preloads the next clip to frame 0. When the
 * playing clip ends we just cross-fade opacity to the already-decoded layer and
 * start it — no blank frame, on any browser.
 *
 * The clip list (default + reactions) is generated by tools/build.js from the
 * Sidewolf*.webm files in assets/webm/. (alphaSrc maps each to the .mp4 twin on
 * Safari — see src/system/video-format.js.)
 */
'use strict';

import { SIDEWOLF } from './sidewolf-clips.js';
import { alphaSrc } from '../system/video-format.js';   // WebM → HEVC-alpha .mp4 on Safari

const first = document.getElementById('side-wolf');
const IDLE_LOOPS = 1;          // loop the default this many times before a reaction

// Gaff dev tool: the "Animations" button toggles a label showing the clip name.
const animLabel = document.getElementById('wolf-animation-label');
const animBtn   = document.getElementById('btn-show-animations');

if (first && SIDEWOLF.default) {
  // ── build the second, identical layer stacked on top of the first ──
  first.classList.add('side-wolf-layer');
  const second = first.cloneNode(false);
  second.removeAttribute('id');
  second.removeAttribute('src');
  second.removeAttribute('data-alpha-src');
  first.removeAttribute('data-alpha-src');      // we drive the src ourselves now
  first.after(second);

  const layers = [first, second];
  layers.forEach(v => {
    v.loop = false; v.muted = true; v.playsInline = true;
    v.setAttribute('playsinline', ''); v.preload = 'auto';
  });

  let active = first, buffer = second;          // active = visible & playing
  let activeMode = 'idle';                       // 'idle' | 'special'
  let idlesPlayed = 0;                           // idle loops in the current streak
  let lastSpecial = -1;
  let queued = false;                            // a tap asks for a reaction next
  let bufferKind = 'idle';                       // what's primed in `buffer`
  let swapping = false;

  const baseName = v => ((v && (v.__logical || v.getAttribute('src'))) || '').split('/').pop();
  function show(v) { v.style.opacity = '1'; v.style.pointerEvents = 'auto'; }
  function hide(v) { v.style.opacity = '0'; v.style.pointerEvents = 'none'; }

  /** pick a random reaction clip, never repeating the previous one */
  function pickReaction() {
    const list = SIDEWOLF.specials;
    if (!list || !list.length) return SIDEWOLF.default;
    let i; do { i = Math.floor(Math.random() * list.length); }
    while (list.length > 1 && i === lastSpecial);
    lastSpecial = i;
    return list[i];
  }

  /** what should follow the current active clip */
  function predictNext() {
    if (queued) return { src: pickReaction(), kind: 'special' };
    if (activeMode === 'idle' && idlesPlayed < IDLE_LOOPS) return { src: SIDEWOLF.default, kind: 'idle' };
    if (activeMode === 'idle') return { src: pickReaction(), kind: 'special' };
    return { src: SIDEWOLF.default, kind: 'idle' };   // after a reaction → idle
  }

  /** load a clip into the hidden buffer layer, ready (paused) at frame 0 */
  function prime(src, kind) {
    bufferKind = kind;
    buffer.__logical = src;
    const real = alphaSrc(src);
    if (buffer.getAttribute('src') !== real) buffer.setAttribute('src', real);
    try { buffer.pause(); } catch (e) {}
    try { buffer.currentTime = 0; } catch (e) {}
    try { buffer.load(); } catch (e) {}
  }
  function primeNext() { const n = predictNext(); prime(n.src, n.kind); }

  /** the active clip finished → cross to the preloaded buffer with no blank frame */
  function onEnded(e) {
    if (e.target !== active || swapping) return;   // only the playing layer drives swaps
    swapping = true;

    // adopt the buffered clip as the new active
    if (bufferKind === 'idle') { activeMode = 'idle'; idlesPlayed += 1; }
    else { activeMode = 'special'; idlesPlayed = 0; queued = false; }

    try { buffer.currentTime = 0; } catch (err) {}
    buffer.play().catch(() => {});
    show(buffer); hide(active);
    try { active.pause(); } catch (err) {}
    if (animLabel) animLabel.textContent = baseName(buffer);

    const justPlayed = active;
    active = buffer; buffer = justPlayed;          // swap roles
    swapping = false;
    primeNext();                                   // preload the following clip
  }

  layers.forEach(v => v.addEventListener('ended', onEnded));

  // tap the wolf → queue a reaction; preload it now so the swap stays gapless
  layers.forEach(v => v.addEventListener('pointerdown', () => {
    queued = true;
    if (bufferKind !== 'special') prime(pickReaction(), 'special');
  }));

  // "Animations" gaff button → show/hide the current clip name under the wolf
  if (animBtn && animLabel) {
    animBtn.addEventListener('click', () => {
      const on = animLabel.style.display === 'none' || !animLabel.style.display;
      animLabel.style.display = on ? 'block' : 'none';
      animBtn.classList.toggle('is-active', on);
      if (on) animLabel.textContent = baseName(active);
    });
  }

  // ── start: play the idle on the active layer, preload what's next ──
  hide(buffer);
  active.__logical = SIDEWOLF.default;
  active.setAttribute('src', alphaSrc(SIDEWOLF.default));
  activeMode = 'idle'; idlesPlayed = 1;            // first idle counts as played
  show(active);
  try { active.currentTime = 0; } catch (e) {}
  active.play().catch(() => {});
  if (animLabel) animLabel.textContent = baseName(active);
  primeNext();

  // muted autoplay can still be blocked until the first gesture — kick it then
  if (active.paused) {
    const kick = () => { active.play().catch(() => {}); };
    document.addEventListener('pointerdown', kick, { once: true });
    document.addEventListener('keydown', kick, { once: true });
  }
}
