/**
 * @module side-wolf
 * @description Gives the left-side SideWolf character a lively, dynamic feel.
 * He loops his default idle clip a few times, then plays ONE randomly-chosen
 * reaction (dances, sniffs, fist-pump, tips his hat, …) once, and returns to
 * idle — forever. Every clip starts and ends in the same pose, so the swaps are
 * seamless.
 *
 * The clip list (default + reactions) is generated by tools/build.js from the
 * Sidewolf*.webm files in assets/webm/ — so adding a new animation and
 * rebuilding automatically folds it into the rotation.
 */
'use strict';

import { SIDEWOLF } from './sidewolf-clips.js';
import { alphaSrc } from '../system/video-format.js';   // WebM → HEVC-alpha .mp4 on Safari

const video = document.getElementById('side-wolf');
const IDLE_LOOPS = 1;        // loop the default this many times before a reaction

// Gaff dev tool: the "Animations" button toggles a label showing the clip name.
const animLabel = document.getElementById('wolf-animation-label');
const animBtn   = document.getElementById('btn-show-animations');

if (video && SIDEWOLF.default) {
  video.loop = false;        // we manage looping ourselves so we can count
  video.muted = true;

  let mode = 'idle';
  let idleCount = 0;
  let lastSpecial = -1;
  let queued = false;        // a click asks for a reaction at the NEXT natural clip end

  /** Point the video at `src` (only swapping the source if it changed) and play. */
  function play(src) {
    const real = alphaSrc(src);   // .webm on Chrome/FF, .mp4 (HEVC-alpha) on Safari
    if (video.getAttribute('src') !== real) video.setAttribute('src', real);
    try { video.currentTime = 0; } catch (e) {}
    video.play().catch(() => {});
    if (animLabel) animLabel.textContent = src.split('/').pop();   // keep the dev label current
  }

  function playIdle() { mode = 'idle'; play(SIDEWOLF.default); }

  function playReaction() {
    const list = SIDEWOLF.specials;
    if (!list || !list.length) { playIdle(); return; }   // no reactions → just idle
    mode = 'special';
    let i;
    do { i = Math.floor(Math.random() * list.length); }
    while (list.length > 1 && i === lastSpecial);         // avoid repeating the last one
    lastSpecial = i;
    play(list[i]);
  }

  video.addEventListener('ended', () => {
    // a queued click takes priority — but only fires now that the clip finished,
    // so the wolf is back in his default pose before switching
    if (queued) { queued = false; idleCount = 0; playReaction(); return; }
    if (mode === 'idle') {
      if (++idleCount >= IDLE_LOOPS) { idleCount = 0; playReaction(); }
      else play(SIDEWOLF.default);        // same clip → seamless re-loop
    } else {
      playIdle();                         // reaction finished → back to idle
    }
  });

  // click / tap the wolf to QUEUE a random reaction for the moment the current
  // clip ends (he finishes the loop and returns to default first — no jarring cut)
  video.addEventListener('pointerdown', () => { queued = true; });

  // "Animations" gaff button → show/hide the current clip name under the wolf
  if (animBtn && animLabel) {
    animBtn.addEventListener('click', () => {
      const on = animLabel.style.display === 'none' || !animLabel.style.display;
      animLabel.style.display = on ? 'block' : 'none';
      animBtn.classList.toggle('is-active', on);
      if (on) animLabel.textContent = (video.getAttribute('src') || '').split('/').pop();
    });
  }

  // start the idle loop (muted autoplay; if the browser blocks it, kick off on
  // the first interaction)
  playIdle();
  if (video.paused) {
    const kick = () => { video.play().catch(() => {}); };
    document.addEventListener('pointerdown', kick, { once: true });
    document.addEventListener('keydown', kick, { once: true });
  }
}
