/* AUTO-GENERATED by tools/build.js — SideWolf animation clips. Do not edit. */
'use strict';
export const SIDEWOLF = {
  "default": "assets/webm/Sidewolf.webm",
  "specials": [
    "assets/webm/Sidewolf_bandana.webm",
    "assets/webm/Sidewolf_blows.webm",
    "assets/webm/Sidewolf_chillin.webm",
    "assets/webm/Sidewolf_confused.webm",
    "assets/webm/Sidewolf_dance2.webm",
    "assets/webm/Sidewolf_dances.webm",
    "assets/webm/Sidewolf_excited.webm",
    "assets/webm/Sidewolf_fighting.webm",
    "assets/webm/Sidewolf_fistpump.webm",
    "assets/webm/Sidewolf_grins.webm",
    "assets/webm/Sidewolf_hat.webm",
    "assets/webm/Sidewolf_headtilt.webm",
    "assets/webm/Sidewolf_jig.webm",
    "assets/webm/Sidewolf_laughing.webm",
    "assets/webm/Sidewolf_neck.webm",
    "assets/webm/Sidewolf_polite.webm",
    "assets/webm/Sidewolf_posture.webm",
    "assets/webm/Sidewolf_sniffing.webm",
    "assets/webm/Sidewolf_sniffs.webm",
    "assets/webm/Sidewolf_tilt.webm"
  ]
};
