/**
 * @module side-wolf
 * @description Gives the left-side SideWolf character a lively, dynamic feel.
 * He loops his default idle clip, then plays ONE randomly-chosen reaction
 * (dances, sniffs, fist-pump, tips his hat, …) once, and returns to idle —
 * forever. Every clip starts and ends in the same pose, so the swaps look
 * seamless.
 *
 * GAPLESS PRE-ROLL CROSSBUFFER — why two videos:
 * A single <video> blanks while it loads/decodes the next src, and on Safari a
 * finished transparent HEVC clip can briefly CLEAR (go transparent) the instant
 * it ends. So we keep TWO stacked, identical layers and cross over *before* the
 * current clip finishes, while it's still painting live frames:
 *   1. one layer plays while the other silently preloads the next clip to frame 0
 *   2. a short moment BEFORE the playing clip ends, we start the buffer and raise
 *      it on top (z-index) — still hidden
 *   3. the instant the buffer paints its first frame (requestVideoFrameCallback)
 *      we reveal it; being on top + opaque, it fully covers the still-live clip
 *   4. only then do we hide/pause the old layer
 * The visible layer is therefore never blank or cleared — no flicker, any browser.
 *
 * The clip list (default + reactions) is generated by tools/build.js from the
 * Sidewolf*.webm files in assets/webm/. (alphaSrc maps each to the .mp4 twin on
 * Safari — see src/system/video-format.js.)
 */
'use strict';

import { SIDEWOLF } from './sidewolf-clips.js';
import { alphaSrc, IS_IOS } from '../system/video-format.js';   // WebM → HEVC-alpha .mp4 on Safari

const first = document.getElementById('side-wolf');
const IDLE_LOOPS = 1;          // loop the default this many times before a reaction
const LEAD = 0.18;             // start the next clip this many seconds before the current ends

// Gaff dev tool: the "Animations" button toggles a label showing the clip name.
const animLabel = document.getElementById('wolf-animation-label');
const animBtn   = document.getElementById('btn-show-animations');

/* ── iOS: lean single-video idle loop ──────────────────────────────────────
   iPhone/iPad software-decode HEVC-alpha and throttle the number of videos that
   can decode at once. The desktop double-buffer (2 wolf layers) + reaction swaps
   starved the decoder → the wolf vanished and the whole game stuttered. A single
   static-src looping idle clip is exactly what the standalone test proved plays
   smoothly, so on iOS we run just that — no second layer, no reaction swaps. */
if (first && SIDEWOLF.default && IS_IOS) {
  first.classList.add('side-wolf-layer');
  first.loop = true; first.muted = true; first.playsInline = true;
  first.setAttribute('playsinline', '');
  first.removeAttribute('data-alpha-src');
  first.setAttribute('src', alphaSrc(SIDEWOLF.default));
  first.style.opacity = '1';
  first.play().catch(() => {});
  if (first.paused) {                       // muted autoplay blocked → start on first touch
    const kick = () => { first.play().catch(() => {}); };
    document.addEventListener('pointerdown', kick, { once: true });
    document.addEventListener('touchstart', kick, { once: true, passive: true });
  }
}

if (first && SIDEWOLF.default && !IS_IOS) {
  // ── build the second, identical layer stacked on top of the first ──
  first.classList.add('side-wolf-layer');
  const second = first.cloneNode(false);
  second.removeAttribute('id');
  second.removeAttribute('src');
  second.removeAttribute('data-alpha-src');
  first.removeAttribute('data-alpha-src');      // we drive the src ourselves now
  first.after(second);

  const layers = [first, second];
  layers.forEach(v => {
    v.loop = false; v.muted = true; v.playsInline = true;
    v.setAttribute('playsinline', ''); v.preload = 'auto';
  });

  let active = first, buffer = second;          // active = visible & playing
  let activeMode = 'idle';                       // 'idle' | 'special'
  let idlesPlayed = 0;                           // idle loops in the current streak
  let lastSpecial = -1;
  let bufferKind = 'idle';                       // what's primed in `buffer`
  let swapping = false;
  let crossTimer = 0;

  const baseName = v => ((v && (v.__logical || v.getAttribute('src'))) || '').split('/').pop();
  function show(v) { v.style.opacity = '1'; }
  function hide(v) { v.style.opacity = '0'; }

  /** pick a random reaction clip, never repeating the previous one */
  function pickReaction() {
    const list = SIDEWOLF.specials;
    if (!list || !list.length) return SIDEWOLF.default;
    let i; do { i = Math.floor(Math.random() * list.length); }
    while (list.length > 1 && i === lastSpecial);
    lastSpecial = i;
    return list[i];
  }

  /** what should follow the current active clip */
  function predictNext() {
    if (activeMode === 'idle' && idlesPlayed < IDLE_LOOPS) return { src: SIDEWOLF.default, kind: 'idle' };
    if (activeMode === 'idle') return { src: pickReaction(), kind: 'special' };
    return { src: SIDEWOLF.default, kind: 'idle' };   // after a reaction → idle
  }

  /** load a clip into the hidden buffer layer, ready (paused) at frame 0 */
  function prime(src, kind) {
    bufferKind = kind;
    buffer.__logical = src;
    const real = alphaSrc(src);
    if (buffer.getAttribute('src') !== real) buffer.setAttribute('src', real);
    try { buffer.pause(); } catch (e) {}
    try { buffer.currentTime = 0; } catch (e) {}
    try { buffer.load(); } catch (e) {}
  }
  function primeNext() { const n = predictNext(); prime(n.src, n.kind); }

  /** arm the cross-over to fire LEAD seconds before the active clip ends */
  function scheduleCross() {
    clearTimeout(crossTimer); crossTimer = 0;
    const d = active.duration;
    if (!d || !isFinite(d)) return;                 // unknown duration → 'ended' fallback covers us
    const ms = Math.max(0, (d - (active.currentTime || 0) - LEAD) * 1000);
    crossTimer = setTimeout(beginCross, ms);
  }

  /**
   * Cross to the preloaded buffer while the active clip is STILL PLAYING live
   * frames, so the visible wolf never blanks. The buffer is raised on top and
   * only revealed once it has actually painted a frame.
   */
  function beginCross() {
    if (swapping) return;
    swapping = true;
    clearTimeout(crossTimer); crossTimer = 0;

    buffer.style.zIndex = '2';                      // buffer sits ON TOP of the live active
    active.style.zIndex = '1';
    try { buffer.play().catch(() => {}); } catch (e) {}

    let done = false;
    const reveal = () => {
      if (done) return; done = true;
      show(buffer);                                 // painting + on top → fully covers the live clip
      if (bufferKind === 'idle') { activeMode = 'idle'; idlesPlayed += 1; }
      else { activeMode = 'special'; idlesPlayed = 0; }
      if (animLabel) animLabel.textContent = baseName(buffer);

      hide(active);                                 // now safe to drop the old layer behind
      try { active.pause(); } catch (e) {}
      const justPlayed = active; active = buffer; buffer = justPlayed;   // swap roles
      swapping = false;
      primeNext();                                  // preload the following clip
      scheduleCross();                              // arm the next transition
    };

    if (typeof buffer.requestVideoFrameCallback === 'function') {
      buffer.requestVideoFrameCallback(() => reveal());   // fires when frame 0 is on screen
      setTimeout(reveal, 120);                            // safety net (< LEAD: active still live)
    } else {
      setTimeout(reveal, 40);
    }
  }

  // fallback: if a clip reaches its natural end before a cross was armed/fired
  function onEnded(e) { if (e.target === active && !swapping) beginCross(); }
  // once a (re)started clip knows its duration, (re)arm the cross
  function onMeta(e) { if (e.target === active && !swapping && !crossTimer) scheduleCross(); }
  layers.forEach(v => {
    v.addEventListener('ended', onEnded);
    v.addEventListener('loadedmetadata', onMeta);
  });

  // "Animations" gaff button → show/hide the current clip name under the wolf
  if (animBtn && animLabel) {
    animBtn.addEventListener('click', () => {
      const on = animLabel.style.display === 'none' || !animLabel.style.display;
      animLabel.style.display = on ? 'block' : 'none';
      animBtn.classList.toggle('is-active', on);
      if (on) animLabel.textContent = baseName(active);
    });
  }

  // ── start: play the idle on the active layer, preload what's next ──
  hide(buffer);
  active.style.zIndex = '2'; buffer.style.zIndex = '1';
  active.__logical = SIDEWOLF.default;
  active.setAttribute('src', alphaSrc(SIDEWOLF.default));
  activeMode = 'idle'; idlesPlayed = 1;            // first idle counts as played
  show(active);
  try { active.currentTime = 0; } catch (e) {}
  active.play().catch(() => {});
  if (animLabel) animLabel.textContent = baseName(active);
  primeNext();
  scheduleCross();                                 // arm the first cross (onMeta re-arms if duration is late)

  // muted autoplay can still be blocked until the first gesture — kick it then
  if (active.paused) {
    const kick = () => { active.play().catch(() => {}); };
    document.addEventListener('pointerdown', kick, { once: true });
    document.addEventListener('keydown', kick, { once: true });
  }
}
