/**
 * tools/build.js — bundle js/*.js (ES modules) into a single classic script app.js.
 *
 * WHY: the game is opened as a double-clicked file (file:// protocol), and
 * browsers block native ES-module imports over file://. This bundles the clean
 * module source into one plain <script> that runs anywhere.
 *
 * WORKFLOW: edit the modules in js/, then run:  node tools/build.js
 * (index.html loads the generated app.js.)
 *
 * It wraps each module in its own scope with a tiny CommonJS-style require(),
 * transforming `import {x} from './m.js'` → require, and `export` → exports.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/* ════════════════════════════════════════════════════════════════
   GAME-SIZE MANIFEST
   Walk the whole project folder, tally bytes per file type, and write the
   snapshot to js/sizedata.js. The in-game "GAME SIZE" popup reads that file,
   so the number it shows is accurate as of the last `node tools/build.js`.
   (Hidden entries like .git/.DS_Store/.env are skipped — not game content.)
════════════════════════════════════════════════════════════════ */
const SIZE_CATEGORIES = [
  { key: 'video', label: 'Videos', exts: ['mp4', 'webm', 'mov', 'm4v', 'avi'] },
  { key: 'audio', label: 'Audio',  exts: ['mp3', 'wav', 'ogg', 'm4a', 'aac'] },
  { key: 'image', label: 'Images', exts: ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'bmp'] },
  { key: 'code',  label: 'Code',   exts: ['js', 'css', 'html', 'htm', 'json', 'md', 'txt'] },
];
function categoryOf(name) {
  const ext = (name.split('.').pop() || '').toLowerCase();
  const c = SIZE_CATEGORIES.find(c => c.exts.includes(ext));
  return c ? c.key : 'other';
}
function walkSizes(dir, acc) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.')) continue;           // skip hidden (.git, .env, .DS_Store…)
    const full = join(dir, e.name);
    if (e.isDirectory()) walkSizes(full, acc);
    else if (e.isFile()) {
      const { size } = statSync(full);
      const k = categoryOf(e.name);
      (acc.cats[k] ||= { bytes: 0, files: 0 });
      acc.cats[k].bytes += size; acc.cats[k].files += 1;
      acc.totalBytes += size;    acc.fileCount += 1;
    }
  }
  return acc;
}
function generateSizeManifest() {
  const acc = walkSizes(root, { cats: {}, totalBytes: 0, fileCount: 0 });
  const labelFor = k => (SIZE_CATEGORIES.find(c => c.key === k)?.label) || 'Other';
  const categories = Object.entries(acc.cats)
    .map(([key, v]) => ({ key, label: labelFor(key), bytes: v.bytes, files: v.files }))
    .sort((a, b) => b.bytes - a.bytes);
  const data = {
    totalBytes: acc.totalBytes,
    fileCount:  acc.fileCount,
    generatedAt: new Date().toISOString().slice(0, 10),
    categories,
  };
  writeFileSync(join(root, 'js', 'sizedata.js'),
    `/* AUTO-GENERATED by tools/build.js — folder-size snapshot. Do not edit. */\n` +
    `'use strict';\nexport const SIZE_MANIFEST = ${JSON.stringify(data, null, 2)};\n`);
  return data;
}
const sizeManifest = generateSizeManifest();   // must run BEFORE module discovery below

// Auto-discover every module in js/ (so adding a new module never needs editing
// this list). Order doesn't matter — require() pulls dependencies on demand —
// but 'main' is the entry point that's required at the end.
const MODULES = readdirSync(join(root, 'js'))
  .filter(f => f.endsWith('.js'))
  .map(f => f.replace(/\.js$/, ''));
if (!MODULES.includes('main')) throw new Error('js/main.js (entry point) not found');

/** Turn one ES-module source into a require()/exports factory body. */
function transform(src) {
  const exported = [];
  const collect = /export\s+(?:async\s+function|function|const|class)\s+(\w+)/g;
  let m;
  while ((m = collect.exec(src))) exported.push(m[1]);

  let body = src
    .replace(/^\s*'use strict';\s*$/m, '')
    // named imports (may span multiple lines):  import { a, b } from './x.js';
    .replace(/import\s*\{([\s\S]*?)\}\s*from\s*['"]\.\/(\w+)\.js['"];?/g, 'const {$1} = require("$2");')
    // side-effect imports:  import './x.js';
    .replace(/import\s*['"]\.\/(\w+)\.js['"];?/g, 'require("$1");')
    // drop the `export ` keyword (declarations stay as normal)
    .replace(/export\s+(?=(?:async\s+function|function|const|class)\b)/g, '');

  if (exported.length) body += `\nObject.assign(exports, { ${exported.join(', ')} });\n`;
  return body;
}

let out = `/* ════════════════════════════════════════════════════════════════
   AUTO-GENERATED — do not edit by hand.
   Bundled from js/*.js by tools/build.js so the game runs from a
   double-clicked file:// page. Edit the modules in js/, then rebuild:
       node tools/build.js
════════════════════════════════════════════════════════════════ */
(function () {
  'use strict';
  const __cache = {};
  const __mods = {};
  function require(name) {
    if (__cache[name]) return __cache[name];
    const exports = {};
    __cache[name] = exports;       // set before running, to tolerate cycles
    __mods[name](exports, require);
    return __cache[name];
  }
`;

for (const name of MODULES) {
  const src = readFileSync(join(root, 'js', `${name}.js`), 'utf8');
  out += `\n  __mods[${JSON.stringify(name)}] = function (exports, require) {\n${transform(src)}\n  };\n`;
}

out += `\n  require('main');\n})();\n`;

writeFileSync(join(root, 'app.js'), out);
console.log(`Bundled ${MODULES.length} modules → app.js`);
console.log(`Game size: ${(sizeManifest.totalBytes / 1048576).toFixed(1)} MB across ${sizeManifest.fileCount} files → js/sizedata.js`);
